### ISSUE TITLE
2 ДЗ

### ISSUE THREAD

**Issue by Nazgul-WK** [Nazgul-WK/Back-end-EGO#10]
- [ ] . Напечатайте на экран сообщение о текущей дате и погоде в этот день #21
- [ ] .Скорость света равна 1 079 252 848,8 километров в час. Выведите на экран сообщение #22
- [ ] Посчитаем количество наименований продуктов, которые нужно сегодня купить.#23
- [ ] Теперь нужно поочередно вывести каждое наименование продукта. #24
- [ ] Сейчас нам нужно вывести наименование продукта только, если количество букв в
нем четное. #25
- [ ] Определить, является ли число простым #26
- [ ] Числа Фибоначчи #27
